/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/profile': typeof ProfileRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/profile': typeof ProfileRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/profile': typeof ProfileRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/controls'
    | '/goals'
    | '/habits'
    | '/login'
    | '/nutrition'
    | '/profile'
    | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/controls'
    | '/goals'
    | '/habits'
    | '/login'
    | '/nutrition'
    | '/profile'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/controls'
    | '/goals'
    | '/habits'
    | '/login'
    | '/nutrition'
    | '/profile'
    | '/workouts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlsRoute: typeof ControlsRoute
  GoalsRoute: typeof GoalsRoute
  HabitsRoute: typeof HabitsRoute
  LoginRoute: typeof LoginRoute
  NutritionRoute: typeof NutritionRoute
  ProfileRoute: typeof ProfileRoute
  WorkoutsRoute: typeof WorkoutsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlsRoute: ControlsRoute,
  GoalsRoute: GoalsRoute,
  HabitsRoute: HabitsRoute,
  LoginRoute: LoginRoute,
  NutritionRoute: NutritionRoute,
  ProfileRoute: ProfileRoute,
  WorkoutsRoute: WorkoutsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
